name = "quantt-calendar"
main = "src/worker.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[kv_namespaces]]
binding = "SCHEDULE_KV"
id = "8259ae409611497aa2e94f6fb4b2a140"
